name: Bug 反馈（使用中文）
description: 出现了一些小问题？
labels: ['错误']
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 在提问之前...
      description: 您在此处发布新 Issue 会导致全体开发者的电子邮箱收到一封提醒邮件，请通过确认以下条目以节省所有人的时间。
      options:
      - label: 我反馈的问题在零协会 BiliBili 动态没有相应近期公告
        required: true
      - label: 我反馈的问题不属于已关闭/已解决的其它 Issue
        required: true
      - label: 我已在未仔细阅读这些内容的情况下勾选所有选项，并相信这不会影响问题的处理
        required: false
      - label: 我使用的模组版本为最新版
        required: true
      - label: 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
        required: true
      - label: 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
        required: true
  - type: textarea
    id: describe
    attributes:
      label: 问题描述
      description: 尽可能详细描述你的问题
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 日志文件
      description: |
        **上传 /Logs 目录下的最新日志文件**
        **请直接将完整的文件拖拽进来，而非自己裁切的片段；若文件体积过大可压缩后再上传**
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: |
        如果有，添加屏幕截图以帮助解释你的问题，包括但不限于游戏画面截图
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: 还有别的吗？
      description: |
        操作系统？相关的配置？链接？参考资料？
        任何能让我们对你所遇到的问题有更多了解的东西
    validations:
      required: false
