name: mirrorchyan_release

on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        required: false

jobs:
  mirrorchyan:
    runs-on: macos-latest

    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "LLC_MOD_Toolbox_Installer.exe"
          mirrorchyan_rid: LLC_MOD_Toolbox
          tag: ${{ inputs.tag }}

          os: win
          arch: x64

          owner: LocalizeLimbusCompany
          repo: LLC_MOD_Toolbox
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}

      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "LLC_MOD_Toolbox.7z"
          mirrorchyan_rid: LLC_MOD_Toolbox_Increment
          tag: ${{ inputs.tag }}
          p7zip: true

          os: win
          arch: x64

          owner: LocalizeLimbusCompany
          repo: LLC_MOD_Toolbox
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
