name: mirrorchyan_release_note

on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        required: false
  release:
    types: [edited]

jobs:
  mirrorchyan:
    runs-on: macos-latest

    steps:
      - id: uploading
        uses: MirrorChyan/release-note-action@v1
        with:
          mirrorchyan_rid: LLC_MOD_Toolbox
          version_name: ${{ inputs.tag }}

          owner: LocalizeLimbusCompany
          repo: LLC_MOD_Toolbox
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}

      - id: uploading_increment
        uses: MirrorChyan/release-note-action@v1
        with:
          mirrorchyan_rid: LLC_MOD_Toolbox_Increment
          version_name: ${{ inputs.tag }}

          owner: LocalizeLimbusCompany
          repo: LLC_MOD_Toolbox
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
